### ISSUE TITLE
linking to the data

### ISSUE THREAD

**Issue by romunov** [Mnemati/Machine-Learning-Approaches-in-COVID-19-Survival-Analysis#1]
To the best of my abilitis, I am unable to find any data on the website [linked to in the paper](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30119-5/fulltext). The only thing I see is a pdf with a list of authors and their affiliations. Can you point me to a specific file?

**Comment by Mnemati** [comment]
Dear Roman,

I hope everything is good at your end.

I apologize for my late response. I checked their website and you are
totally right. The dataset was related to a research study and their
authors have provided a link to their github which contained a csv file
(dataset). At this point, I was unable to find their github like you so I
will send them an email and request them to share the data again or provide
a link to their data.

Once I hear from them, I will get back to you and share what they will tell
me regarding the data. Thank you for your patience.

Best,
Mo

**Comment by shi-ang** [comment]
Hi Mo,

I was looking at your Cell Pattern paper and also having difficulty finding the data. Is there any specific website I can check? Have you heard back from them?

Best,
Shiang

**Comment by Mnemati** [comment]
Hi,

I hope you are doing well. I had lost track of how I obtained the data but
I finally found it and saved in my github repository (
https://github.com/Mnemati/Machine-Learning-Approaches-in-COVID-19-Survival-Analysis).
The data's name is latestdata.tar.gz

Best,
Mo
