### ISSUE TITLE
algorithm 

### ISSUE THREAD

**Issue by IppiliPraveen** [Mnemati/Machine-Learning-Approaches-in-COVID-19-Survival-Analysis#2]
1. which algorithm  you are used here in this code ?
2. please send answer my quarry .
@Mnemati

**Comment by StefanoFedeli** [comment]
Good evening,
Thank you for sharing with us the code and the data but as much as I tried, I'm very much unable to reproduce the results showed in the paper using your code in the repository and the Sksurv library. 
My CoxPHSurivivalAnalysis() take in input a simple dataset like the one below:
`columns: age_0-34,age_35-46,age_45-60,age_60+,sex_female,sex_male`
`count: 1182`

I'm a correctly understanding your preprocessing before fitting the different models?

Thanks for the help

**Comment by Mnemati** [comment]
Dear Stefano,

I hope all is well,

I see that you are treating the age as a categorical variable as one of
your inputs to the CoxPhSurvival algorithm. I treated the age as a
continuous variable to use for the CoxPH.

The reason that I categorized age into 4 different groups is that I wanted
to compare the survival function of different age groups. So, by
categorizing the age, I was able to Kaplan Meier algorithm and plot ther
survival function of 4 different age groups.

So, if you treat age as a continuous variable, you should be able to
reproduce the same c-indices as reported in the paper.

Best wishes,
Mo

**Comment by Mnemati** [comment]
Dear Stefano, 

I see that you are treating the age as a categorical variable to

**Comment by Mnemati** [comment]
Dear Stefano,

I hope all is well,

I see that you are treating the age as a categorical variable as one of your inputs to the CoxPhSurvival algorithm. I treated the age as a continuous variable to use for the CoxPH.

The reason that I categorized age into 4 different groups is that I wanted to compare the survival function of different age groups. So, by categorizing the age, I was able to Kaplan Meier algorithm and plot ther survival function of 4 different age groups. 

So, if you treat age as a continuous variable, you should be able to reproduce the same c-indices as reported in the paper. 

Best wishes,
Mo

**Comment by StefanoFedeli** [comment]
Dear Mohammadreza,

Thank you for your quick reply to my question but unfortunately I cannot yet achieve the results even though I'm treating age as a continuous variable having also the same quantiles that you showed in the paper. It is true that my CoxPHSurvivalAnalysis() is not hypertuned but stillthe C-score ( coming from CoxPHSurvivalAnalysis.score() ) is quite off the target :\ 
```
df = 
               age   sex_female     sex_male
count  1182.000000  1182.000000  1182.000000
mean     46.808456     0.463621     0.536379
std      16.975090     0.498886     0.498886
min       0.000000     0.000000     0.000000
25%      34.000000     0.000000     0.000000
50%      46.404228     0.000000     1.000000
75%      60.000000     1.000000     1.000000
max      96.000000     1.000000     1.000000
COX: 60.2, (59.2,61.2)




X_train, X_test, y_train, y_test = train_test_split(df, data_y, test_size = 0.33)
coxph = CoxPHSurvivalAnalysis()
coxph.fit(X_train,y_train)
coxph.score(X_test,y_test)
```

I will try some hyper parameter tuning and maybe other functions to compute the c-score but if you have some hints I would be happy to hear, maybe you were in the same situation at your first trial.
